import type {Metadata} from "next";
import "./globals.css";
import {ReactNode} from "react";
import localFont from "next/font/local";
import ClientLayout from "@/components/Layout/ClinetLayout";
import {Toaster} from "react-hot-toast";
import {getServerSession} from "next-auth";
import {authOptions} from "@/lib/authOptions";


const Dana = localFont({
    src: [
        {path: "/fonts/Dana-Regular.woff2", weight: "400", style: "normal"},
        {path: "/fonts/Dana-Medium.woff2", weight: "500", style: "normal"},
        {path: "/fonts/Dana-DemiBold.woff2", weight: "600", style: "normal"},
        {path: "/fonts/Dana-Bold.woff2", weight: "700", style: "normal"},
    ],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({children}: Readonly<{ children: ReactNode }>) {
    const session = await getServerSession(authOptions);

    return (
        <html lang="fa" dir="rtl">
        <body className={Dana.className}>
        <ClientLayout session={session}>
            <Toaster/>
            {children}
        </ClientLayout>
        </body>
        </html>
    );
}
